// const translations = {
//   az: {
//     individual: "İcbari <br/> sığorta",
//     corporate: "siğorta <br/> ödənişi",
//     home: "ANA SƏHİFƏ",
//     services: "Məhsullarımız",
//     about: "Şirkət haqqında",
//     presentation: "servislər",
//     contact: "ƏLAQƏ",
//     slide1_title: "Bize güvənin, gələcəyinizi <br /> Heyat Sığortası ilə təmin edin!",
//     slide2_title: "Daşınmaz Əmlakınızın <br />İcbari Sığortası Bizimlə",
//     slide3_title: "KASKO Sığortasında<br />Etibarlı Tərəfdaşınız",
//     apply: "Müraciət et",
//     car_insurance: "Avtomobilin icbari sığortası",
//     life_insurance: "Həyat sığortası",
//     property_insurance: "Əmlak sığortası",
//     travel_insurance: "Səyahət sığortası",
//     casco_insurance: "KASKO sığorta",
//     company_name: "Sığorta",
//     about_animals: "Kiçik dostlarımızı qoruyaq, onların bizə ehtiyacı var",

//     about_description:
//       "Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br />Accusantium magni labore facere, nisi quod unde ut eveniet quisquam explicabo,<br />laudantium iste corrupti aliquam eos nesciunt asperiores officiis, sapiente assumenda! Assumenda nemo<br />",
//     more_info: "Ətraflı",
//     satisfied_clients: "Razı müştəri",
//     years_experience: "İl təcrübə",
//     partners: "Əməkdaş"
//   },
//   ru: {
//     individual: "Обязательное <br/> страхование",
//     corporate: "Страховые <br/> выплаты",
//     home: "Главная",
//     services: "Продукты",
//     about: "О компании",
//     presentation: "услуги",
//     contact: "Контакты",
//     slide1_title: "Доверьтесь нам, обеспечьте свое будущее <br /> с помощью страхования жизни!",
//     slide2_title: "Обязательное страхование<br />Недвижимости с нами",
//     slide3_title: "Ваш надежный партнер<br />в страховании КАСКО",
//     apply: "Подать заявку",
//     car_insurance: "Обязательное страхование автомобиля",
//     life_insurance: "Страхование жизни",
//     property_insurance: "Страхование имущества",
//     travel_insurance: "Страхование путешествий",
//     casco_insurance: "КАСКО страхование",
//     company_name: "Сигорта",
//     about_animals: "Давайте защитим наших маленьких друзей, они нуждаются в нас",

//     about_description:
//       "Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br />Accusantium magni labore facere, nisi quod unde ut eveniet quisquam explicabo,<br />лаудантиум исте коррупти аликам eos несциент аспериорес officiis, sapiente assumenda! Assumenda nemo<br />",
//     more_info: "Подробнее",
//     satisfied_clients: "Довольные клиенты",
//     years_experience: "Лет опыта",
//     partners: "Партнеры"
//   },
//   en: {
//     individual: "Mandatory <br/> Insurance",
//     corporate: "Insurance <br/> Payments",
//     home: "Home",
//     services: "Products",
//     about: "About the Company",
//     presentation: "Services",
//     contact: "Contact",
//     slide1_title: "Trust us, secure your future <br /> with Life Insurance!",
//     slide2_title: "Mandatory Insurance<br />For Your Real Estate With Us",
//     slide3_title: "Your Reliable Partner<br />in CASCO Insurance",
//     apply: "Apply",
//     car_insurance: "Car Liability Insurance",
//     life_insurance: "Life Insurance",
//     property_insurance: "Property Insurance",
//     travel_insurance: "Travel Insurance",
//     casco_insurance: "CASCO Insurance",
//     company_name: "Insurance",
//     about_animals: "Let's protect our little friends, they need us",

//     about_description:
//       "Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br />Accusantium magni labore facere, nisi quod unde ut eveniet quisquam explicabo,<br />laudantium iste corrupti aliquam eos nesciunt asperiores officiis, sapiente assumenda! Assumenda nemo<br />",
//     more_info: "More Info",
//     satisfied_clients: "Satisfied Clients",
//     years_experience: "Years of Experience",
//     partners: "Partners"
//   },
// };

const translations = {
  az: {
    compulsory: "İcbarİ <br /> sİğorta",
    payment: "sİğorta <br /> ödənİşİ",
    home: "ANA SƏHİFƏ",
    product: "Məhsullarımız",
    life_insurance: "Həyat siğortası",
    casko_insurance: "Kasko siğortası",
    property_insurance: "Əmlak siğortası",
    car_insurance: "Avtomobilin icbari siğortası",
    travel_insurance: "Səyahət siğortası",
    about_company: "Şİrkət haqqında",
    info: "Məlumat",
    management: "Rəhbərlik",
    mission: "Missiya",
    biznes: "Biznesə yanaşma",
    legislation: "Qanunvericilik",
    vacancy: "Vakansiya",
    questions: "Ən çox verilən suallar",
    services: "Servİslər",
    certificate_check: "Şəhadətnamə yoxlama <span class='text-[.6rem]'>(icbari siğortanın yoxlanışı)</span>",
    insurance_payment: "Siğorta ödənişi",
    penalty_check: "Cərimə yoxla",
    penalty_payment: "Cərimə ödənişi",
    customs_calculator: "Gömrük kalkulyatoru",
    contact: "ƏLAQƏ",
    slide1_title: "Bize güvənin gələcəyinizi <br /> Heyat Sığortası ilə təmin edin!",
    slide2_title: "Daşınmaz Əmlakınızın <br />İcbari Sığortası Bizimlə",
    slide3_title: "KASKO Sığortasında<br />Etibarlı Tərəfdaşınız",
    apply: "Müraciət et",
    car_insurance: "Avtomobilin icbari sığortası",
    life_insurance: "Həyat sığortası",
    property_insurance: "Əmlak sığortası",
    protect_friends: "Kiçik dostlarımızı qoruyaq onların bizə ehtiyaçları var",
    about_description:
      "Kiçik dostlarınızın gözlənilməz hallarda qorunması üçün heyvan sığortası ideal bir həll yoludur. Bu sığorta növü yalnız fövqəladə vəziyyətləri əhatə etməklə kifayətlənmir, həm də stasionar və ambulator müalicə, dərman təminatı, görüntüləmə və müayinə kimi geniş xidmətlərdən faydalanma imkanı verir. Bu şəkildə, təcili yardımlarla yanaşı, heyvanınızın sağlamlığını qorumaq üçün lazım olan bütün xidmətlərə rahatlıqla çıxış əldə edirsiniz.",

    satisfied_clients: "Razı müştəri",
    years_experience: "İl təcrübə",
    partners: "Əməkdaş",
    products: "Məhsullar",
    life_insurance: "Həyat Sığortası",
    property_insurance_mandatory: "Daşınmaz əmlakın icbari sığortası",
    car_insurance_mandatory: "İcbari Nəqliyyat sığortası",
    travel_insurance: "Səyahət Sığortası",
    casco_insurance: "KASKO Sığorta",
    learn_more: "Daha ətraflı",
    property_insurance_description: "Daşınmaz əmlakınızı icbari sığorta ilə qoruyun.",
    car_insurance_description: "Nəqliyyat vasitələrinizi icbari sığorta ilə təmin edin.",
    casco_insurance_description: "KASKO sığorta ilə avtomobilinizi təhlükələrdən qoruyun.",
    travel_insurance_description: "Səyahət sığortası ilə rahat bir səfər planlayın.",
    life_insurance_description: "Həyat sığortası ilə gələcəyinizi təhlükəsiz hala gətirin.",
    voluntary_health_insurance: "Könüllü Tibbi Sığorta",
    voluntary_health_insurance_description: "Könüllü Tibbi Sığorta haqqında məlumat.",
    cargo_insurance: "Yük sığortası",
    cargo_insurance_description: "Yük sığortası haqqında məlumat.",
    green_card_system: "Yaşıl Kart Sistemi",
    green_card_system_description: "Yaşıl Kart Sistemi haqqında məlumat.",
    voluntary_property_insurance: "Daşınmaz Əmlakın Könüllü Sığortası",
    voluntary_property_insurance_description: "Daşınmaz Əmlakın Könüllü Sığortası haqqında məlumat.",

    insurance_tagline: "Siğortanız bir ünvanda",
    website_info:
      "www.1sigorta.az saytı 19.07.2024-cü il tarixində Mircəfər Mirəli oğlu Cəfərov tərəfindən təsis edilmiş, Azərbaycan Respublikası Mərkəzi Bankı tərəfindən verilmiş SA – 0337 saylı lisenziya əsasında sayt üzərindən sığorta fəaliyyətinə başlanmışdır.",
    contact: "Əlaqə",
    phone_number: "+994 55 200 99 95",
    email: "Office@1sigorta.az",
    address: "Bakı ş. Səməd Vurğun küçəsi 34. (AF MALL, 3-cü mərtəbə)",
    car_info_heading: "Avtomobil məlumatlarını daxil edin",
    plate_number_label: "Qeydiyyat nişanı",
    registration_certificate_label: "NV-nin qeydiyyat şəhadətnaməsi",
    mobile_number_label: "Mobil nömrə",
    registration_date_label: "Avtomobilin qeydiyyat tarixi",
    engine_capacity_label: "Mühərrik həcmi",
    electric_car: "Elektrik avtomobili",
    motorcycle: "Motosiklet",
    engine_1500_2000: "1500-2000",
    engine_above_2000: "2000 və üzəri",
    cargo_vehicle: "Yük avtomobili",
    personal_info_heading: "Şəxsi məlumatlarınızı daxil edin",
    id_number_label: "şəxsiyyət Vəsiqəsinin Nömrəsi",
    fin_code_label: "Fərdi indentifikasiya Nömrəsi",
    driver_license_label: "Sürücülük vəsiqənin seriya və nömrəsi",
    continue_button: "davam edin",
    insurance_recommendation:
      "Sığorta şirkətləri barədə reytinq və rəylərlə tanış olduqdan sonra seçim etməyinizi tövsiyə edirik",
    select_button: "Seçin",
    id_option_aze: "AZE",
    id_option_aa: "AA",
    auto_insurance_title: "İcbari Avto Sığorta",
    online_insurance_paragraph_1:
      "Online İcbari Avto Sığorta almaq artıq BirSigorta.az icbari sigorta bürosu ilə daha asandır. Bunun üçün sizə cəmi 1 dəqiqə kifayətdir ki, icbari avtomobil sığortanızı onlayn olaraq ala biləsiniz. Texnologiyanın inkişaf etməsi nəticəsində online sığorta xidmətləri də yaranmağa başladı. Onlayn İcbari Avto Sığorta kimi digər sığorta xidmətləri də sizə artıq onlayn şəkildə təqdim edirik. Sığorta qiymətlərini də onlayn şəkildə ödənişləri etmək imkan artıq çox sadə bir şəkildə mümkündür. Evdən çıxmadan bütün sığorta işlərinizi həll edə bilərsiniz. İcbari sigorta bürosu sizə sığorta şərtlərini ən uyğun şəkildə təqdim edir. Avtonəqliyyat vasitələrinin icbari sığortası yoxlamaq ximdətindən yararlana bilərsiniz.",
    mandatory_insurance_office_title: "İcbari Sığorta Bürosu - BirSigorta.az",
    online_insurance_paragraph_2:
      "İcbari Sığorta Bürosu kimi BirSigorta.az icbari sığorta xidmətlərini indi çox asan bir formada, onlayn şəkildə cəmi 1 dəqiqə ərzində həyata keçirmək imkanı verir. İcbari sığorta bürosu əsas vəzifə olaraq icbari sığortalarla bağlı olan bütün müraciətləri vaxtında və ya aydın bir şəkildə cavablayır, yaranan problemləri tez bir zamanda həll edir. İcbari sığorta bürosu sizə bir çox sığorta şirkətlərinin xidmətlərini təqdim edir, uyğun olan xidmət növündən asanalıqla istifadə edə bilərsiniz. İndi müraciət etmək çox asan və tez bir zamanda mümkündür. Avtonəqliyyat vasitələrinin icbari sığortası yoxlamaq indi sığorta bürolarının ən əhəmiyyətli işlərindən birinə çevrilib. Zamanlar bu xidmət onlayn şəkildə də təqdim edilməyə başlamışdır.",
    mandatory_auto_insurance_heading: "İcbari Avtomobil Sığortası",
    mandatory_auto_insurance_paragraph:
      "İcbari Avtomobil Sığortası - Qanunvericiliklə tələb olunan və yol nəqliyyat hadisəsi nəticəsində üçüncü şəxslərə zərər yetirildikdə sığorta kompensasiyasının verilməsini nəzərədə tutan sığorta növüdür. İcbari Avto Sığorta qəza zamanı qarşı tərəfə verdiyiniz zərərə 5000 AZN-dək təminat verir. Avtonəqliyyat vasitələrinin icbari sığortası yoxlamaq üçün hadisə zamanı siz sığorta mütəxəssisini və yol polisini hadisə yerinə dəvət edərək hadisəni müvafiq formatda aktlaşdırırsınız. Daha sonra isə sığorta şirkətiniz sizin üçün dəymiş zərərin miqyasını müəyyən edərək avto nəqliyyat vasitənizin təmiri üçün ödəniş edir və ya müvafiq avtomobil servisində təmir etdirərək sizə təhvil verir.",
    isb_bonus_malus_heading: "İcbari Sığorta Bürosu (İSB) və bonus-malus sistemi",
    isb_bonus_malus_paragraph:
      "İcbari Sığorta Bürosu bildiyiniz kimi icbari sığorta ödənişlərinə və bu ödənişlərin hesablanmasında istifadə olunan bonus-malus sisteminə nəzarət edir. Bu sistem daxilində İSB tərəfindən sizin qəzasız keçirdiyiniz hər sığorta ilinə görə bonus hesablanır sürücüyə. Nəticə etibarı ilə rəsmi şəkildə sizi mükafatlandırmış olur. Əks hal baş verəndə isə sizə malus hesablanaraq cərimə kimi tətbiq olunur. İSB.az bununla da sürücüləri daha məsuliyyətli olmağa, qaydalara riayət etməyə çağırmış olur.",
    read_more_button: "Ətraflı oxu",
    auto_insurance_heading: "Avtomobil Siğortası və İcbari siğorta",
    auto_insurance_paragraph_1:
      "Avtomobil Siğortası siğorta şirkətləri tərəfindən bir neçə formada təklif edilir. Rəsmi qaydalara əsasən istənilən nəqliyyat vasitəsinin İcbari Avto Siğortası olmaq məcburiyyəti vardır. Onlayn İcbari Avtomobil Siğortası olmadığı təqdirdə siz qanunla müəyyən edilmiş məbləğdə cərimələnəcəksiniz. İcbari siğorta sizə 5000 manatadək təminat vəd edir. Bu da sizin qarşılaşacağınız xoşa gəlməz hallarda daha rahat olmanız üçün dövlət tərəfindən yaradılmış imkandır.",
    online_auto_insurance_check_heading: "Avto siğorta yoxlamaq onlayn formada",
    online_auto_insurance_check_paragraph:
      "Avto siğorta yoxlamaq xidmətimizdən sizdə faydalana bilərsiniz. Avtonəqliyyat vasitələrinin icbari siğortası yoxlamaq xidməti sizə əlverişli və münasib şərtlərlə təqdim edilir. Siğorta etdirdikdən sonra ən xırda detalları belə sizin üçün onlayn yaranmış siğorta profilindən baxa və nəzarət edə bilərsiniz. Hər hansı bir dəyişiklik olsa, burada öz əksini tapır. Şəxsiyyət vəsiqəsi və ya avtomobilin qeydiyyat nişanı kimi məlumatları daxil etməklə avto siğorta yoxlamaq imkanından istifadə edə bilərsiniz. Çox asan bir formada, sayta daxil olaraq avto siğorta yoxlamaq əməliyyatını həyata keçirə bilərsiniz. Mobil telefonlar vasitəsi ilə də çox asanlıqla avto siğorta işlərini həyata keçirə bilərsiniz.",
    ensure_future_heading: "İcbari Avto Siğorta ilə Gələcəyinizi Təmimat Altına Alın!",
    ensure_future_paragraph:
      "Avtomobillərin icbari siğortası haqqında bütün qanunlar “İcbari siğortalar haqqında” Azərbaycan Respublikası Qanununun 4-cü fəsilində qeyd olunmuşdur. Avtomobillərin siğorta olunması olduqca vacibdir. Çünki ölkədəki nəqliyyat sıxlığı sayəsində tez-tez qəzalar baş verə bilir. Bu səbəbdən avtomobil sahibləri xeyli miqdarda məbləğ ödəyərək maddi ziyana uğrayırlar. İcbari siğorta sayəsində siz təminat olaraq avtomobilinizə dəymiş ziyanı ödəməkdən azad ola bilirsiniz. Həmçinin siğorta ödənişlərinizi unutduğunuz zaman saytımıza daxil olaraq burada yoxlaya bilmək imkanına da sahibsiniz.",
    compensation_amount_heading:
      "Avtonəqliyyat vasitəsi sahiblərinin mülki məsuliyyətinin icbari siğortası zamanı ödəniləcək məbləğlər:",
    compensation_1: "Bir fiziki şəxsin sağlamlığına dəyən zərər üzrə - 5 000 (beş min) AZN",
    compensation_2: "Ümumi olaraq sağlamlığa dəyən zərər üzrə - 50 000 (əlli min) AZN",
    compensation_3: "Üçüncü şəxslərin əmlakına dəyən zərər üzrə - 5 000 (beş min) AZN",
    compensation_4: "Bir hadisə üzrə - 55 000 (əlli beş min) AZN",
    property_insurance_advice_paragraph:
      "Adından da göründüyü kimi sizin üçün vacib olan bütün əmlaklarınızın siğortası gələcəyiniz üçün edə biləcəyiniz əsas zəmanətlərdən biridir. Ona görə də avtomobilinizi siğorta etdirməyi unutmayın və insure.az kimi etibarlı siğorta şirkətlərinə müraciət etməyinizi tövsiyə edirik.",
    online_insurance_advantage_heading: "Onlayn İcbari siğorta vaxt qazandırır",
    online_insurance_advantage_paragraph:
      "Onlayn icbari siğorta almaq sizin üçün əlavə vaxt qazandırır. Müxtəlif siğorta agentlərinin sizi zəng edib narahat etməsindən narahat olmusunuzsa insure.az ilə onlayn icbari avto siğorta ala bilərsiniz. Bunun üçün sizə sadəcə şəxsi məlumatlarınızın yəni - şəxsiyyət vəsiqəsi, sürücülük vəsiqəsi və texpassport lazım olacaq. Daha sonra siğorta şirkətini seçərək icbari avto siğorta müqaviləniz üçün nəzərdə tutulmuş məbləği ödəyə biləcəksiniz. Siğorta ödənişini həyata keçirdikdən sonra, sizin avtonəqliyyat vasitəniz siğorta edilmiş olacaq və rahatlıqla avtonəqliyyat vasitənizi idarə edə bilərsiniz.",
    online_auto_insurance_advantage_heading: "Onlayn İcbari Avto Siğorta almağın üstünlükləri",
    online_auto_insurance_advantage_paragraph:
      "Onlayn İcbari Avto Siğorta almağın üstünlükləri barədə deyə bilərik ki, cərimələr hazırda yollarda quraşdırılmış kameralar tərəfindən avtomatik olaraq edilir. Bunu nəzərə alaraq maksimum dərəcədə çalışmalısınız ki, maşın siğortası bitmədən siz yeni siğortanızı əldə edəsiniz. Əgər icbari siğorta bitibsə siğortanızı yeniləmədən nəqliyyat vasitənizi idarə etməməlisiniz. Hazırda isə icbari siğortanızı lazım olan anda yeniləyə bilməyiniz üçün insure.az onlayn siğorta platforması var. Siz insure.az saytı vasitəsi ilə maşın üçün icbari avto siğortanı 1 dəqiqə ərzində əldə edərək yolunuza rahatlıqla davam edə biləcəksiniz.",
    isb_info_heading: "İcbari Siğorta Bürosu (İSB) nədir?",
    isb_info_paragraph:
      "İcbari siğortalar haqqında Qanunla nəzərdə tutulanların yerinə yetirilməsi üçün həmin qanunun tələbləri nəzərə alınmaqla AR-ın Mülki Məcəlləsinə uyğun olaraq hüquqi şəxslərin ittifaqı kimi təsis edilib və fəaliyyət göstərir. İcbari Siğorta Bürosu (İSB) özlüyündə siğorta olunanların, zərərçəkən və zərər vurulan şəxslərin müdafiəsini, icbari siğorta ilə bağlı sisteminin sabitliyi və inkişafını təmin etmək üçün yaradılmışdır. Siz də ola biləcək hər hansı narahatçılığınız üçün birbaşa İSB-yə müraciət edə bilərsiniz. İcbari Siğorta Bürosu sizin müraciətinizi qeydə alaraq, araşdıracaq və hüquqi olaraq sizə yardımçı olacaqdır.",
    isb_activity_heading: "İSB az fəaliyyəti nədən ibarətdir?",
    isb_activity_paragraph:
      "Siğorta şirkətləri birlikdə İSB az - ın təməlini qoymuş və formalaşdırmışdır. Bu da özündə o mənanı ifadə edir ki, İSB az həm dövlət qurumu olaraq nəzarət edici mövqeyə malikdir, həm də şirkətlərin ortaq marağını qoruyan fərdi qurum səlahiyyətlərinə malikdir.",
    mandatory_insurance_benefits_heading: "İcbari Siğorta Sizə nə qazandırır?",
    mandatory_insurance_benefits_paragraph:
      "İcbari Siğorta alışı artıq tam olaraq onlaynlaşıb. Bununla da siz öz avtonəqliyyat vasitənizə 5000 AZN-dək təminat əldə edirsiniz. Əgər hər hansı qəza hadisəsi olarsa icbari siğorta sizin zərər çəkmiş tərəfə vurduğunuz ziyanın 5000 manatadək olan hissəsini qarşılayacaq. Beləliklə siz, icbari siğorta ilə çox az məbləğ ödəyərək böyük təminat əldə etmiş olursunuz.",
    insurance_calculator_heading: "İcbari siğorta Kalkulyatoru nə üçün lazımdır?",
    insurance_calculator_paragraph:
      "İcbari Siğorta Kalkulyatoru icbari siğortanı online yoxlamaq üçün istifadə edilən yeni bir funksiyadır. İcbari siğortanı online yoxlamaq üçün təqdim edilən, hesablayıcı icbari siğorta kalkulyatoru çox sadə və asan istifadə olunan bir alətdir. İcbari siğorta ilə bağlı hesablamalarınızı icbari siğorta kalkulyatoru vasitəsi ilə asanlıqla edə bilərsiniz.",
  },
  ru: {
    compulsory: "Обязательное <br /> страхование",
    payment: "страховой <br /> платеж",
    home: "ГЛАВНАЯ",
    product: "Наши продукты",
    life_insurance: "Страхование жизни",
    casko_insurance: "КАСКО страхование",
    property_insurance: "Страхование имущества",
    car_insurance: "Обязательное страхование автомобиля",
    travel_insurance: "Страхование путешествий",
    about_company: "О компании",
    info: "Информация",
    management: "Руководство",
    mission: "Миссия",
    biznes: "Подход к бизнесу",
    legislation: "Законодательство",
    vacancy: "Вакансия",
    questions: "Часто задаваемые вопросы",
    services: "Услуги",
    certificate_check: "Проверка сертификата <span class='text-[.6rem]'>(проверка обязательного страхования)</span>",
    insurance_payment: "Страховой платеж",
    penalty_check: "Проверка штрафа",
    penalty_payment: "Оплата штрафа",
    customs_calculator: "Таможенный калькулятор",
    contact: "КОНТАКТЫ",
    slide1_title: "Доверьтесь нам, обеспечьте свое <br/> будущее с помощью <br />  Страхования Жизни!",
    slide2_title: "Обязательное Страхование <br />Вашего Недвижимого Имущества",
    slide3_title: "Ваш надежный партнер <br/> в страховании КАСКО",
    apply: "Подать заявку",
    car_insurance: "Обязательное страхование автомобиля",
    life_insurance: "Страхование жизни",
    property_insurance: "Страхование имущества",
    protect_friends: "Давайте защитим наших маленьких друзей, они нуждаются в нас",
    voluntary_health_insurance: "Добровольное медицинское страхование",
    voluntary_health_insurance_description: "Информация о добровольном медицинском страховании.",
    cargo_insurance: "Страхование грузов",
    cargo_insurance_description: "Информация о страховании грузов.",
    green_card_system: "Система «Зелёная карта»",
    green_card_system_description: "Информация о системе «Зелёная карта».",
    voluntary_property_insurance: "Добровольное страхование недвижимости",
    voluntary_property_insurance_description: "Информация о добровольном страховании недвижимости.",

    about_description:
      "Страхование животных — это идеальное решение для защиты ваших маленьких друзей в непредвиденных ситуациях. Этот вид страхования охватывает не только чрезвычайные ситуации, но и дает возможность воспользоваться широким спектром услуг, таких как стационарное и амбулаторное лечение, обеспечение лекарствами, диагностика и обследование. Таким образом, вы получаете легкий доступ ко всем необходимым услугам для защиты здоровья вашего питомца, помимо экстренной помощи.",
    satisfied_clients: "Довольные клиенты",
    years_experience: "Лет опыта",
    partners: "Партнеры",
    products: "Продукты",
    life_insurance: "Страхование жизни",
    property_insurance_mandatory: "Обязательное страхование недвижимости",
    car_insurance_mandatory: "Обязательное страхование транспорта",
    travel_insurance: "Страхование путешествий",
    casco_insurance: "КАСКО страхование",
    learn_more: "Подробнее",
    casco_insurance_description: "Защитите свой автомобиль от опасностей с помощью страхования КАСКО.",
    travel_insurance_description: "Планируйте безопасное путешествие с помощью страхования путешествий.",
    car_insurance_description: "Обеспечьте свои транспортные средства с помощью обязательного страхования.",
    property_insurance_description: "Защитите свою недвижимость с помощью обязательного страхования.",
    life_insurance_description: "Обеспечьте свое будущее с помощью страхования жизни.",
    insurance_tagline: "Ваша страховка на одном сайте",
    website_info:
      "Сайт www.1sigorta.az был основан 19.07.2024 года Мирджафаром Мирэли оглы Джафаровым и начал <br/> свою деятельность по страхованию на основе лицензии № SA – 0337, выданной Центральным банком Азербайджанской Республики.",
    contact: "Контакты",
    phone_number: "+994 55 200 99 95",
    email: "Office@1sigorta.az",
    address: "г. Баку, ул. Самеда Вургуна, 34. (AF MALL, 3-й этаж)",
    car_info_heading: "Введите данные автомобиля",
    plate_number_label: "Номерной знак",
    registration_certificate_label: "Свидетельство о регистрации ТС",
    mobile_number_label: "Мобильный номер",
    registration_date_label: "Дата регистрации автомобиля",
    engine_capacity_label: "Объем двигателя",
    electric_car: "Электромобиль",
    motorcycle: "Мотоцикл",
    engine_1500_2000: "1500-2000",
    engine_above_2000: "2000 и выше",
    cargo_vehicle: "Грузовой автомобиль",
    personal_info_heading: "Введите свои личные данные",
    id_number_label: "Номер удостоверения личности",
    fin_code_label: "Идентификационный номер",
    driver_license_label: "Серия и номер водительского удостоверения",
    continue_button: "Продолжить",
    insurance_recommendation: "Мы рекомендуем вам выбрать после ознакомления с рейтингами и отзывами о страховых компаниях",
    select_button: "Выбрать",
    id_option_aze: "AZE",
    id_option_aa: "AA",
    auto_insurance_title: "Обязательное Автострахование",
    online_insurance_paragraph_1:
      "Получение онлайн обязательного автострахования стало проще с BirSigorta.az, бюро обязательного страхования. Для этого вам потребуется всего 1 минута, чтобы получить обязательное автострахование онлайн. С развитием технологий также начали появляться онлайн-страховые услуги. Мы уже предоставляем вам другие страховые услуги, такие как обязательное автострахование, в онлайн-режиме. Возможность оплаты страховых взносов онлайн также стала очень простой. Вы можете решить все свои страховые вопросы, не выходя из дома. Бюро обязательного страхования предлагает вам наиболее подходящие условия страхования. Вы можете воспользоваться услугой проверки обязательного страхования транспортных средств.",
    mandatory_insurance_office_title: "Бюро Обязательного Страхования - BirSigorta.az",
    online_insurance_paragraph_2:
      "Как Бюро Обязательного Страхования, BirSigorta.az предлагает обязательные страховые услуги теперь в очень простой форме, онлайн, всего за 1 минуту. Бюро обязательного страхования в качестве основной задачи обеспечивает своевременный или четкий ответ на все запросы, связанные с обязательным страхованием, и быстро решает возникающие проблемы. Бюро обязательного страхования предоставляет вам услуги множества страховых компаний, и вы можете легко воспользоваться подходящим видом услуг. Теперь подать заявку очень легко и можно быстро. Проверка обязательного страхования транспортных средств стала одной из важнейших задач страховых бюро. Со временем эта услуга также начала предоставляться в онлайн-режиме.",
    mandatory_auto_insurance_heading: "Обязательное Автострахование",
    mandatory_auto_insurance_paragraph:
      "Обязательное автострахование - это вид страхования, требуемый законодательством, который предусматривает выплату страховой компенсации в случае нанесения ущерба третьим лицам в результате дорожно-транспортного происшествия. Обязательное автострахование обеспечивает покрытие ущерба, нанесенного другой стороне в результате аварии, до 5000 AZN. Для проверки обязательного страхования транспортных средств при аварии вы вызываете на место происшествия страхового эксперта и дорожную полицию, и оформляете происшествие в соответствующем формате. Затем ваша страховая компания определяет размер нанесенного ущерба и оплачивает ремонт вашего транспортного средства или проводит ремонт в соответствующем автосервисе и передает вам отремонтированное транспортное средство.",
    isb_bonus_malus_heading: "Бюро Обязательного Страхования (ИСБ) и система бонус-малус",
    isb_bonus_malus_paragraph:
      "Бюро Обязательного Страхования контролирует выплаты и систему бонус-малус, которая используется при расчете этих выплат. В рамках этой системы ИСБ начисляет бонус за каждый год без аварий. Таким образом, вы официально вознаграждаетесь. В противном случае вам начисляется малус, который применяется в качестве штрафа. ISB.az также призывает водителей быть более ответственными и соблюдать правила.",
    read_more_button: "Читать дальше",
    auto_insurance_heading: "Автострахование и Обязательное страхование",
    auto_insurance_paragraph_1:
      "Автострахование предлагается страховыми компаниями в нескольких формах. В соответствии с официальными правилами, обязательное автострахование должно быть у любого транспортного средства. Если у вас нет онлайн-обязательного автострахования, вы будете оштрафованы на сумму, установленную законом. Обязательное страхование обеспечивает вам покрытие до 5000 AZN. Это возможность, созданная государством, чтобы вы могли чувствовать себя спокойнее в случае возникновения неприятных ситуаций.",
    online_auto_insurance_check_heading: "Проверка автострахования в онлайн режиме",
    online_auto_insurance_check_paragraph:
      "Вы можете воспользоваться нашей услугой проверки автострахования в онлайн-режиме. Услуга проверки обязательного страхования транспортных средств предлагается вам на выгодных и удобных условиях. После страхования вы можете просмотреть и контролировать даже мельчайшие детали через ваш онлайн-страховой профиль. Если произойдут какие-либо изменения, они отразятся здесь. Вы можете воспользоваться возможностью проверки автострахования, введя такие данные, как удостоверение личности или номерной знак автомобиля. Вы можете легко выполнить операцию проверки автострахования, просто зайдя на сайт. Вы также можете легко осуществить автострахование через мобильные телефоны.",
    ensure_future_heading: "Обеспечьте свое будущее с обязательным автострахованием!",
    ensure_future_paragraph:
      "Все законы об обязательном автостраховании указаны в главе 4 Закона Азербайджанской Республики «Об обязательных страхованиях». Страхование автомобилей крайне важно. В стране часто происходят аварии из-за высокой плотности движения. Из-за этого владельцы автомобилей несут значительные убытки, оплачивая крупные суммы. Благодаря обязательному страхованию вы освобождаетесь от необходимости оплачивать ущерб, нанесенный вашему автомобилю. Вы также можете проверить свои страховые платежи, если забудете о них, посетив наш сайт.",
    compensation_amount_heading:
      "Суммы выплат по обязательному автострахованию гражданской ответственности владельцев транспортных средств:",
    compensation_1: "За ущерб, нанесенный здоровью одного физического лица - 5 000 (пять тысяч) AZN",
    compensation_2: "За общий ущерб, нанесенный здоровью - 50 000 (пятьдесят тысяч) AZN",
    compensation_3: "За ущерб, нанесенный имуществу третьих лиц - 5 000 (пять тысяч) AZN",
    compensation_4: "За одно происшествие - 55 000 (пятьдесят пять тысяч) AZN",
    property_insurance_advice_paragraph:
      "Как видно из названия, страхование всего вашего имущества - это одна из основных гарантий вашего будущего. Поэтому не забудьте застраховать свой автомобиль и обратитесь к надежным страховым компаниям, таким как insure.az.",
    online_insurance_advantage_heading: "Онлайн обязательное страхование экономит время",
    online_insurance_advantage_paragraph:
      "Получение онлайн обязательного страхования экономит ваше время. Если вас беспокоят звонки от различных страховых агентов, вы можете приобрести онлайн обязательное автострахование с insure.az. Для этого вам понадобятся ваши личные данные, а именно - удостоверение личности, водительское удостоверение и технический паспорт. Затем вы сможете выбрать страховую компанию и оплатить сумму, предусмотренную для вашего обязательного автострахования. После оплаты страхового взноса ваше транспортное средство будет застраховано, и вы сможете спокойно управлять своим автомобилем.",
    online_auto_insurance_advantage_heading: "Преимущества получения онлайн обязательного автострахования",
    online_auto_insurance_advantage_paragraph:
      "О преимуществах получения онлайн обязательного автострахования можно сказать, что штрафы в настоящее время фиксируются автоматическими камерами на дорогах. Учитывая это, вы должны постараться максимально вовремя получить новую страховку до истечения срока действия старой. Если обязательное страхование истекло, не управляйте транспортным средством, не обновив страховку. В настоящее время существует онлайн-страховая платформа insure.az, которая позволяет вам обновить обязательную страховку в нужный момент. С помощью сайта insure.az вы можете получить обязательное автострахование для своего автомобиля всего за 1 минуту и продолжить свой путь без проблем.",
    isb_info_heading: "Что такое Бюро Обязательного Страхования (ИСБ)?",
    isb_info_paragraph:
      "Бюро Обязательного Страхования (ИСБ) было создано для обеспечения выполнения требований Закона об обязательных страхованиях. ИСБ обеспечивает защиту застрахованных, пострадавших и тех, кто причинил ущерб, а также стабильность и развитие системы обязательного страхования. Вы можете напрямую обратиться в ИСБ в случае возникновения каких-либо проблем. Бюро Обязательного Страхования зафиксирует ваш запрос, проведет расследование и окажет вам юридическую помощь.",
    isb_activity_heading: "Чем занимается ИСБ аз?",
    isb_activity_paragraph:
      "Страховые компании объединились, чтобы создать и сформировать ИСБ аз, который выступает как государственный орган с контролирующей ролью, а также обладает полномочиями защищать общие интересы компаний.",
    mandatory_insurance_benefits_heading: "Что вам дает Обязательное Страхование?",
    mandatory_insurance_benefits_paragraph:
      "Покупка Обязательного Страхования теперь полностью онлайн. Таким образом, вы получаете покрытие до 5000 AZN для вашего транспортного средства. Если произойдет авария, обязательное страхование покроет ущерб, нанесенный пострадавшей стороне, до 5000 манатов. Таким образом, вы получаете большую гарантию, заплатив небольшую сумму за обязательное страхование.",
    insurance_calculator_heading: "Для чего нужен Калькулятор Обязательного Страхования?",
    insurance_calculator_paragraph:
      "Калькулятор Обязательного Страхования - это новый инструмент, используемый для проверки обязательного страхования онлайн. Этот калькулятор прост и удобен в использовании. Вы можете легко выполнить расчеты по обязательному страхованию с помощью калькулятора обязательного страхования.",
  },
  en: {
    compulsory: "Compulsory <br /> insurance",
    payment: "Insurance <br /> payment",
    home: "HOME",
    product: "Our Products",
    life_insurance: "Life Insurance",
    casko_insurance: "CASKO Insurance",
    property_insurance: "Property Insurance",
    car_insurance: "Compulsory Car Insurance",
    travel_insurance: "Travel Insurance",
    about_company: "About Company",
    info: "Information",
    management: "Management",
    mission: "Mission",
    biznes: "Business Approach",
    legislation: "Legislation",
    vacancy: "Vacancy",
    questions: "Frequently Asked Questions",
    services: "Services",
    certificate_check: "Certificate Check <span class='text-[.6rem]'>(compulsory insurance verification)</span>",
    insurance_payment: "Insurance Payment",
    penalty_check: "Check Penalty",
    penalty_payment: "Penalty Payment",
    customs_calculator: "Customs Calculator",
    contact: "CONTACT",
    slide1_title: "Trust us and secure your future <br /> with Life Insurance!",
    slide2_title: "Compulsory Insurance <br />of Your Real Estate",
    slide3_title: "Your Reliable Partner <br/> in CASKO Insurance",
    apply: "Apply",
    car_insurance: "Compulsory Car Insurance",
    life_insurance: "Life Insurance",
    voluntary_health_insurance: "Voluntary Health Insurance",
    voluntary_health_insurance_description: "Information about voluntary health insurance.",
    cargo_insurance: "Cargo Insurance",
    cargo_insurance_description: "Information about cargo insurance.",
    green_card_system: "Green Card System",
    green_card_system_description: "Information about the Green Card System.",
    voluntary_property_insurance: "Voluntary Property Insurance",
    voluntary_property_insurance_description: "Information about voluntary property insurance.",

    property_insurance: "Property Insurance",
    protect_friends: "Let's protect our little friends, they need us",
    about_description:
      "Pet insurance is an ideal solution for protecting your little friends in unforeseen circumstances. This type of insurance not only covers emergencies but also provides access to a wide range of services such as inpatient and outpatient treatment, medication provision, diagnostics, and examinations. This way, in addition to emergency care, you have easy access to all the services necessary to protect your pet's health.",
    satisfied_clients: "Satisfied Clients",
    years_experience: "Years of Experience",
    partners: "Partners",
    products: "Products",
    life_insurance: "Life Insurance",
    property_insurance_mandatory: "Compulsory Property Insurance",
    car_insurance_mandatory: "Compulsory Transport Insurance",
    travel_insurance: "Travel Insurance",
    casco_insurance: "CASKO Insurance",
    life_insurance_description: "Secure your future with life insurance.",
    property_insurance_description: "Protect your property with compulsory insurance.",
    car_insurance_description: "Ensure your vehicles with compulsory insurance.",
    travel_insurance_description: "Plan a safe trip with travel insurance.",
    casco_insurance_description: "Protect your car from dangers with CASKO insurance.",
    learn_more: "Learn More",
    insurance_tagline: "Your insurance in one place",
    website_info:
      "The website www.1sigorta.az was established on 19.07.2024 by Mirjafar Mirali oghlu Jafarov <br/> and started its insurance activities under license number SA – 0337 issued by the Central Bank of the Republic of Azerbaijan.",
    contact: "Contact",
    phone_number: "+994 55 200 99 95",
    email: "Office@1sigorta.az",
    address: "Baku, Samed Vurgun Street 34. (AF MALL, 3rd floor)",
    car_info_heading: "Enter Car Information",
    plate_number_label: "License Plate Number",
    registration_certificate_label: "Vehicle Registration Certificate",
    mobile_number_label: "Mobile Number",
    registration_date_label: "Car Registration Date",
    engine_capacity_label: "Engine Capacity",
    electric_car: "Electric Car",
    motorcycle: "Motorcycle",
    engine_1500_2000: "1500-2000",
    engine_above_2000: "2000 and above",
    cargo_vehicle: "Cargo Vehicle",
    personal_info_heading: "Enter Your Personal Information",
    id_number_label: "ID Card Number",
    fin_code_label: "Personal Identification Number",
    driver_license_label: "Driver's License Series and Number",
    continue_button: "Continue",
    insurance_recommendation: "We recommend you to choose after reviewing ratings and feedback on insurance companies",
    select_button: "Select",
    id_option_aze: "AZE",
    id_option_aa: "AA",
    auto_insurance_title: "Mandatory Auto Insurance",
    online_insurance_paragraph_1:
      "Getting online Mandatory Auto Insurance is now easier with BirSigorta.az, the mandatory insurance bureau. It takes just 1 minute to get your mandatory auto insurance online. As technology advances, online insurance services have also emerged. We now offer you other insurance services like Mandatory Auto Insurance online. The ability to make insurance payments online has also become very simple. You can handle all your insurance matters without leaving home. The mandatory insurance bureau offers you the most suitable insurance conditions. You can take advantage of the service to check the mandatory insurance of vehicles.",
    mandatory_insurance_office_title: "Mandatory Insurance Bureau - BirSigorta.az",
    online_insurance_paragraph_2:
      "As a Mandatory Insurance Bureau, BirSigorta.az now provides mandatory insurance services in a very easy, online format, taking just 1 minute. The mandatory insurance bureau ensures timely or clear responses to all requests related to mandatory insurance and quickly resolves arising issues. The mandatory insurance bureau offers you the services of many insurance companies, allowing you to easily use the appropriate service. Now applying is very easy and quick. Checking the mandatory insurance of vehicles has become one of the most important tasks of insurance bureaus. Over time, this service has also started to be offered online.",
    mandatory_auto_insurance_heading: "Mandatory Auto Insurance",
    mandatory_auto_insurance_paragraph:
      "Mandatory Auto Insurance is a type of insurance required by law that provides compensation if damage is caused to third parties as a result of a road traffic accident. Mandatory Auto Insurance provides coverage of up to 5000 AZN for damage caused to the other party in an accident. To check the mandatory insurance of vehicles during an accident, you invite the insurance expert and traffic police to the scene and document the incident in the appropriate format. Then, your insurance company determines the extent of the damage and either pays for the repair of your vehicle or repairs it at the appropriate auto service and hands it over to you.",
    isb_bonus_malus_heading: "Mandatory Insurance Bureau (ISB) and the bonus-malus system",
    isb_bonus_malus_paragraph:
      "The Mandatory Insurance Bureau monitors payments and the bonus-malus system used in calculating these payments. Under this system, the ISB calculates a bonus for each insurance year you spend without an accident, officially rewarding you. If the opposite happens, a malus is calculated and applied as a penalty. ISB.az also calls on drivers to be more responsible and follow the rules.",
    read_more_button: "Read more",
    auto_insurance_heading: "Auto Insurance and Mandatory Insurance",
    auto_insurance_paragraph_1:
      "Auto Insurance is offered by insurance companies in several forms. According to official regulations, any vehicle is required to have Mandatory Auto Insurance. If you do not have online Mandatory Auto Insurance, you will be fined the amount set by law. Mandatory insurance provides you with coverage of up to 5000 AZN. This is an opportunity created by the state to help you feel more at ease in unpleasant situations.",
    online_auto_insurance_check_heading: "Checking Auto Insurance Online",
    online_auto_insurance_check_paragraph:
      "You can take advantage of our online auto insurance check service. The service of checking the mandatory insurance of vehicles is offered to you under favorable and convenient conditions. After insuring, you can view and control even the smallest details through your online insurance profile. If any changes occur, they are reflected here. You can use the auto insurance check feature by entering details such as your ID card or vehicle registration number. You can easily carry out the auto insurance check operation by simply visiting the website. You can also easily handle auto insurance matters through mobile phones.",
    ensure_future_heading: "Ensure Your Future with Mandatory Auto Insurance!",
    ensure_future_paragraph:
      "All laws regarding Mandatory Auto Insurance are stated in Chapter 4 of the Law of the Republic of Azerbaijan “On Mandatory Insurance”. Insuring vehicles is very important. Frequent accidents can occur due to the heavy traffic density in the country. Because of this, car owners pay large sums and suffer financial losses. With mandatory insurance, you are exempt from paying for damage to your vehicle as a guarantee. You can also check your insurance payments on our website if you forget them.",
    compensation_amount_heading: "Compensation amounts for mandatory auto insurance of vehicle owners' civil liability:",
    compensation_1: "For damage to the health of one person - 5 000 (five thousand) AZN",
    compensation_2: "For total damage to health - 50 000 (fifty thousand) AZN",
    compensation_3: "For damage to third-party property - 5 000 (five thousand) AZN",
    compensation_4: "For one incident - 55 000 (fifty-five thousand) AZN",
    property_insurance_advice_paragraph:
      "As the name suggests, insuring all of your important properties is one of the main guarantees you can make for your future. Therefore, don't forget to insure your car and consult reliable insurance companies like insure.az.",
    online_insurance_advantage_heading: "Online Mandatory Insurance Saves Time",
    online_insurance_advantage_paragraph:
      "Getting online mandatory insurance saves you time. If you are worried about calls from various insurance agents, you can purchase online mandatory auto insurance with insure.az. For this, you will only need your personal information, such as an ID card, driver's license, and technical passport. Then, you can select an insurance company and pay the amount specified for your mandatory auto insurance contract. After completing the insurance payment, your vehicle will be insured, and you can drive your vehicle with peace of mind.",
    online_auto_insurance_advantage_heading: "Advantages of Getting Online Mandatory Auto Insurance",
    online_auto_insurance_advantage_paragraph:
      "Regarding the advantages of getting online mandatory auto insurance, it can be said that fines are now automatically issued by cameras installed on the roads. Considering this, you should make every effort to obtain a new insurance policy before your existing one expires. If your mandatory insurance has expired, you should not drive your vehicle without renewing the insurance. There is now an online insurance platform, insure.az, that allows you to renew your mandatory insurance at the right time. Through the insure.az website, you can obtain mandatory auto insurance for your vehicle within 1 minute and continue your journey without any problems.",
    isb_info_heading: "What is the Mandatory Insurance Bureau (ISB)?",
    isb_info_paragraph:
      "The Mandatory Insurance Bureau (ISB) was established to ensure the implementation of the requirements of the Law on Mandatory Insurance. The ISB ensures the protection of insured persons, victims, and those who cause damage, as well as the stability and development of the mandatory insurance system. You can also contact the ISB directly if you have any concerns. The Mandatory Insurance Bureau will record your request, investigate, and provide you with legal assistance.",
    isb_activity_heading: "What does ISB az do?",
    isb_activity_paragraph:
      "Insurance companies have come together to establish and form ISB az, which acts as a government agency with a supervisory role and also has the authority to protect the common interests of companies.",
    mandatory_insurance_benefits_heading: "What does Mandatory Insurance give you?",
    mandatory_insurance_benefits_paragraph:
      "Purchasing Mandatory Insurance is now completely online. This way, you get coverage of up to 5000 AZN for your vehicle. If an accident occurs, mandatory insurance will cover up to 5000 manats of the damage you caused to the injured party. Thus, you get significant coverage by paying a small amount for mandatory insurance.",
    insurance_calculator_heading: "What is the Mandatory Insurance Calculator for?",
    insurance_calculator_paragraph:
      "The Mandatory Insurance Calculator is a new tool used to check mandatory insurance online. The mandatory insurance calculator provided for checking is very simple and easy to use. You can easily perform calculations related to mandatory insurance using the mandatory insurance calculator.",
  },
};

function changeLanguage(language) {
  document.querySelectorAll("[data-key]").forEach((element) => {
    const key = element.getAttribute("data-key");
    element.innerHTML = translations[language][key];
  });
}
